default: &default
  pool: 5
  timeout: 5000
  adapter: sqlite3

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
  #adapter: postgresql
  #database: bluefox_db
  #username: bluefox
  #password:
  #port: 5432
  #host: localhost
